apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: nginx
  listeners:
    - name: http-redirect
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    # - name: star-CHANGEME
    #   hostname: "*.CHANGEME"
    #   port: 443
    #   protocol: HTTPS
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: wildcard-certificate
    # - name: CHANGEME
    #   hostname: "CHANGEME"
    #   port: 443
    #   protocol: HTTPS
    #   allowedRoutes:
    #     namespaces:
    #       from: All
    #   tls:
    #     mode: Terminate
    #     certificateRefs:
    #       - name: wildcard-certificate
    