apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: nginx-gateway
spec:
  dnsNames:
  - "*.sigil.box"
  - "sigil.box"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: wildcard-cert
  usages:
  - digital signature
  - key encipherment
