apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    chart: cert-manager
    helm:
      values: |-
        installCRDs: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt
            spec:
              acme:
                email: info@sigil.box
                privateKeySecretRef:
                  name: letsencrypt-issuer-account-key
                server: https://acme-v02.api.letsencrypt.org/directory
                solvers:
                - dns01:
                    cloudflare:
                      apiTokenSecretRef:
                        key: CF_API_TOKEN
                        name: cf-api-token
                      email: info@sigil.box
                  selector:
                    dnsZones:
                    - sigil.box
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
