apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    chart: cert-manager
    helm:
      values: |-
        installCRDs: true
        config:
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
          enableGatewayAPI: true
        extraObjects:
          # - |
          #   apiVersion: external-secrets.io/v1beta1
          #   kind: ExternalSecret
          #   metadata:
          #     name: cf-api-key
          #   spec:
          #     secretStoreRef:
          #       kind: ClusterSecretStore
          #       name: CHANGEME
          #     target:
          #       name: CHANGEME
          #       creationPolicy: Owner
          #     dataFrom:
          #     - extract:
          #         key: CHANGEME
          #     refreshInterval: 1m
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt
            spec:
              acme:
                email: CHANGEME
                privateKeySecretRef:
                  name: letsencrypt-issuer-account-key
                server: https://acme-v02.api.letsencrypt.org/directory
                solvers:
                - dns01:
                    cloudflare:
                      apiTokenSecretRef:
                        key: api-token
                        name: CHANGEME
                      email: CHANGEME
                  selector:
                    dnsZones:
                    - CHANGEME
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
