---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-manifests
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/unattended-backpack/canon
    path: gitops/nginx-gateway-manifests/testnet
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
