---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: app-of-apps
spec:
  project: default
  source:
    repoURL: https://github.com/unattended-backpack/canon
    path: gitops/nginx-gateway-fabric
    targetRevision: master
    helm:
      releaseName: nginx-gateway
      valueFiles:
        - testnet-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
