---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: app-of-apps
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.2.5
    chart: reloader
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
