apiVersion: v1
kind: Secret
metadata:
  name: gitops
  namespace: argocd
  labels:
    app.kubernetes.io/instance: argocd
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/unattended-backpack/canon
  project: default
  name: gitops